name: dbus_onemw
version: 0.7.3+2

description:
  LG extension of a native Dart implementation of the D-Bus message bus client.

homepage: https://github.com/LibertyGlobal/onemw-dbus-dart

environment:
  sdk: '>=2.15.0 <3.0.0'

platforms:
  linux:
  windows:

dependencies:
  args: ^2.0.0
  ffi: ^1.1.2
  meta: ^1.3.0
  xml: ^6.1.0
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
  test_cov: ^1.0.1

executables:
  dart-dbus: dart_dbus
